<header>
      <!-- nav bar for the web -->
    <nav class="navbar">
          <!-- web logo -->
        <a class="navbar_brand" href="index.php">
          <img src="../media/image/logo.png" alt="Logo" class="logo_image">
        </a>
        <?php include 'menu.inc'; ?>
        <a class="button" href="../logout.php">Logout</a>
          
        </div>
        
      
    </nav>
    <hr>
  </header>